# Generated by Django 5.1.4 on 2024-12-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Numero de Contacto'),
        ),
    ]
